[package]
name = "rast"
version = "0.1.0"
edition = "2024"

[dependencies]
bmp = "0.5.0"
nalgebra = { version = "0.34.1", features = ["rayon"] }
rayon = "1.11.0"
softbuffer = "0.4.6"
winit = "0.30.12"

[profile.release]
debug = true
